/*
 * This file is generated by jOOQ.
 */
package kpi.hlibsukhoruchkin.kursova.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kpi.hlibsukhoruchkin.kursova.jooq.Keys;
import kpi.hlibsukhoruchkin.kursova.jooq.Kursova;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Shows.ShowsPath;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.records.ScheduleRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schedule extends TableImpl<ScheduleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kursova.schedule</code>
     */
    public static final Schedule SCHEDULE = new Schedule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScheduleRecord> getRecordType() {
        return ScheduleRecord.class;
    }

    /**
     * The column <code>kursova.schedule.ShowID</code>.
     */
    public final TableField<ScheduleRecord, ULong> SHOWID = createField(DSL.name("ShowID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>kursova.schedule.ShowTime</code>.
     */
    public final TableField<ScheduleRecord, LocalDateTime> SHOWTIME = createField(DSL.name("ShowTime"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private Schedule(Name alias, Table<ScheduleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Schedule(Name alias, Table<ScheduleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kursova.schedule</code> table reference
     */
    public Schedule(String alias) {
        this(DSL.name(alias), SCHEDULE);
    }

    /**
     * Create an aliased <code>kursova.schedule</code> table reference
     */
    public Schedule(Name alias) {
        this(alias, SCHEDULE);
    }

    /**
     * Create a <code>kursova.schedule</code> table reference
     */
    public Schedule() {
        this(DSL.name("schedule"), null);
    }

    public <O extends Record> Schedule(Table<O> path, ForeignKey<O, ScheduleRecord> childPath, InverseForeignKey<O, ScheduleRecord> parentPath) {
        super(path, childPath, parentPath, SCHEDULE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SchedulePath extends Schedule implements Path<ScheduleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SchedulePath(Table<O> path, ForeignKey<O, ScheduleRecord> childPath, InverseForeignKey<O, ScheduleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SchedulePath(Name alias, Table<ScheduleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SchedulePath as(String alias) {
            return new SchedulePath(DSL.name(alias), this);
        }

        @Override
        public SchedulePath as(Name alias) {
            return new SchedulePath(alias, this);
        }

        @Override
        public SchedulePath as(Table<?> alias) {
            return new SchedulePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kursova.KURSOVA;
    }

    @Override
    public UniqueKey<ScheduleRecord> getPrimaryKey() {
        return Keys.KEY_SCHEDULE_PRIMARY;
    }

    @Override
    public List<ForeignKey<ScheduleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SCHEDULE_SHOWS_FK);
    }

    private transient ShowsPath _shows;

    /**
     * Get the implicit join path to the <code>kursova.shows</code> table.
     */
    public ShowsPath shows() {
        if (_shows == null)
            _shows = new ShowsPath(this, Keys.SCHEDULE_SHOWS_FK, null);

        return _shows;
    }

    @Override
    public Schedule as(String alias) {
        return new Schedule(DSL.name(alias), this);
    }

    @Override
    public Schedule as(Name alias) {
        return new Schedule(alias, this);
    }

    @Override
    public Schedule as(Table<?> alias) {
        return new Schedule(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Schedule rename(String name) {
        return new Schedule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Schedule rename(Name name) {
        return new Schedule(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Schedule rename(Table<?> name) {
        return new Schedule(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule where(Condition condition) {
        return new Schedule(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schedule where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schedule where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schedule where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schedule where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
