/*
 * This file is generated by jOOQ.
 */
package kpi.hlibsukhoruchkin.kursova.jooq.tables.records;


import kpi.hlibsukhoruchkin.kursova.jooq.tables.Roles;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kursova.roles.RoleID</code>.
     */
    public void setRoleid(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>kursova.roles.RoleID</code>.
     */
    public ULong getRoleid() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>kursova.roles.RoleName</code>.
     */
    public void setRolename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kursova.roles.RoleName</code>.
     */
    public String getRolename() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesRecord
     */
    public RolesRecord() {
        super(Roles.ROLES);
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(ULong roleid, String rolename) {
        super(Roles.ROLES);

        setRoleid(roleid);
        setRolename(rolename);
        resetChangedOnNotNull();
    }
}
