/*
 * This file is generated by jOOQ.
 */
package kpi.hlibsukhoruchkin.kursova.jooq;


import java.util.Arrays;
import java.util.List;

import kpi.hlibsukhoruchkin.kursova.jooq.tables.Channels;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Favourites;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Roles;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Schedule;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Sessions;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Shows;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kursova extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kursova</code>
     */
    public static final Kursova KURSOVA = new Kursova();

    /**
     * The table <code>kursova.channels</code>.
     */
    public final Channels CHANNELS = Channels.CHANNELS;

    /**
     * The table <code>kursova.favourites</code>.
     */
    public final Favourites FAVOURITES = Favourites.FAVOURITES;

    /**
     * The table <code>kursova.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>kursova.schedule</code>.
     */
    public final Schedule SCHEDULE = Schedule.SCHEDULE;

    /**
     * The table <code>kursova.sessions</code>.
     */
    public final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>kursova.shows</code>.
     */
    public final Shows SHOWS = Shows.SHOWS;

    /**
     * The table <code>kursova.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Kursova() {
        super("kursova", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Channels.CHANNELS,
            Favourites.FAVOURITES,
            Roles.ROLES,
            Schedule.SCHEDULE,
            Sessions.SESSIONS,
            Shows.SHOWS,
            Users.USERS
        );
    }
}
