/*
 * This file is generated by jOOQ.
 */
package kpi.hlibsukhoruchkin.kursova.jooq;


import kpi.hlibsukhoruchkin.kursova.jooq.tables.Channels;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Favourites;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Roles;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Schedule;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Sessions;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Shows;
import kpi.hlibsukhoruchkin.kursova.jooq.tables.Users;


/**
 * Convenience access to all tables in kursova.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kursova.channels</code>.
     */
    public static final Channels CHANNELS = Channels.CHANNELS;

    /**
     * The table <code>kursova.favourites</code>.
     */
    public static final Favourites FAVOURITES = Favourites.FAVOURITES;

    /**
     * The table <code>kursova.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>kursova.schedule</code>.
     */
    public static final Schedule SCHEDULE = Schedule.SCHEDULE;

    /**
     * The table <code>kursova.sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>kursova.shows</code>.
     */
    public static final Shows SHOWS = Shows.SHOWS;

    /**
     * The table <code>kursova.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
